name: Preparer CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # https://github.com/actions/cache/blob/master/examples.md#scala---sbt
    - name: Cache SBT ivy cache
      uses: actions/cache@v1.1.2
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}
    # https://github.com/actions/cache/blob/master/examples.md#scala---sbt:
    - name: Cache SBT
      uses: actions/cache@v1.1.2
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    # https://github.com/marketplace/actions/setup-java-jdk
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8.0.241
    - name: Run tests
      run: sbt test
